/*
 * This file is generated by jOOQ.
*/
package c.b.s.common.message.infrastructure.jooq;


import c.b.s.common.message.infrastructure.jooq.tables.TbMesageFile;
import c.b.s.common.message.infrastructure.jooq.tables.TbMessage;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BoxinSaasTenant extends SchemaImpl {

    private static final long serialVersionUID = 2071921965;

    /**
     * The reference instance of <code>boxin_saas_tenant</code>
     */
    public static final BoxinSaasTenant BOXIN_SAAS_TENANT = new BoxinSaasTenant();

    /**
     * The table <code>boxin_saas_tenant.tb_mesage_file</code>.
     */
    public final TbMesageFile TB_MESAGE_FILE = c.b.s.common.message.infrastructure.jooq.tables.TbMesageFile.TB_MESAGE_FILE;

    /**
     * 智牛SaaS平台消息表, owner: guiqingqing, manager: zhengkeshuang
     */
    public final TbMessage TB_MESSAGE = c.b.s.common.message.infrastructure.jooq.tables.TbMessage.TB_MESSAGE;

    /**
     * No further instances allowed
     */
    private BoxinSaasTenant() {
        super("boxin_saas_tenant", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TbMesageFile.TB_MESAGE_FILE,
            TbMessage.TB_MESSAGE);
    }
}
