/*
 * This file is generated by jOOQ.
*/
package c.b.s.common.message.infrastructure.jooq;


import c.b.s.common.message.infrastructure.jooq.tables.TbMesageFile;
import c.b.s.common.message.infrastructure.jooq.tables.TbMessage;
import c.b.s.common.message.infrastructure.jooq.tables.records.TbMesageFileRecord;
import c.b.s.common.message.infrastructure.jooq.tables.records.TbMessageRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.ULong;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>boxin_saas_tenant</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TbMesageFileRecord, Long> IDENTITY_TB_MESAGE_FILE = Identities0.IDENTITY_TB_MESAGE_FILE;
    public static final Identity<TbMessageRecord, ULong> IDENTITY_TB_MESSAGE = Identities0.IDENTITY_TB_MESSAGE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TbMesageFileRecord> KEY_TB_MESAGE_FILE_PRIMARY = UniqueKeys0.KEY_TB_MESAGE_FILE_PRIMARY;
    public static final UniqueKey<TbMessageRecord> KEY_TB_MESSAGE_PRIMARY = UniqueKeys0.KEY_TB_MESSAGE_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<TbMesageFileRecord, Long> IDENTITY_TB_MESAGE_FILE = Internal.createIdentity(TbMesageFile.TB_MESAGE_FILE, TbMesageFile.ID);
        public static Identity<TbMessageRecord, ULong> IDENTITY_TB_MESSAGE = Internal.createIdentity(TbMessage.TB_MESSAGE, TbMessage.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<TbMesageFileRecord> KEY_TB_MESAGE_FILE_PRIMARY = Internal.createUniqueKey(TbMesageFile.TB_MESAGE_FILE, "KEY_tb_mesage_file_PRIMARY", TbMesageFile.ID);
        public static final UniqueKey<TbMessageRecord> KEY_TB_MESSAGE_PRIMARY = Internal.createUniqueKey(TbMessage.TB_MESSAGE, "KEY_tb_message_PRIMARY", TbMessage.ID);
    }
}
