/*
 * This file is generated by jOOQ.
*/
package c.b.s.common.message.infrastructure.jooq;


import c.b.s.common.message.infrastructure.jooq.tables.TbMesageFile;
import c.b.s.common.message.infrastructure.jooq.tables.TbMessage;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in boxin_saas_tenant
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>boxin_saas_tenant.tb_mesage_file</code>.
     */
    public static final TbMesageFile TB_MESAGE_FILE = c.b.s.common.message.infrastructure.jooq.tables.TbMesageFile.TB_MESAGE_FILE;

    /**
     * 智牛SaaS平台消息表, owner: guiqingqing, manager: zhengkeshuang
     */
    public static final TbMessage TB_MESSAGE = c.b.s.common.message.infrastructure.jooq.tables.TbMessage.TB_MESSAGE;
}
