/*
 * This file is generated by jOOQ.
*/
package c.b.s.common.logging.infrastructure.jooq.tables.records;


import c.b.s.common.logging.infrastructure.jooq.tables.CasLoginLog;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * 智牛SaaS平台登录日志表, owner: guiqingqing, manager: zhengkeshuang
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CasLoginLogRecord extends UpdatableRecordImpl<CasLoginLogRecord> implements Record9<ULong, ULong, String, String, String, UByte, Timestamp, Timestamp, Byte> {

    private static final long serialVersionUID = 1335201244;

    /**
     * Setter for <code>boxin_saas_tenant.cas_login_log.id</code>. 主键ID
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.cas_login_log.id</code>. 主键ID
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>boxin_saas_tenant.cas_login_log.user_id</code>. 用户ID
     */
    public void setUserId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.cas_login_log.user_id</code>. 用户ID
     */
    public ULong getUserId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>boxin_saas_tenant.cas_login_log.user_name</code>. 用户名
     */
    public void setUserName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.cas_login_log.user_name</code>. 用户名
     */
    public String getUserName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>boxin_saas_tenant.cas_login_log.real_name</code>. 用户姓名
     */
    public void setRealName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.cas_login_log.real_name</code>. 用户姓名
     */
    public String getRealName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>boxin_saas_tenant.cas_login_log.ip</code>. IP地址
     */
    public void setIp(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.cas_login_log.ip</code>. IP地址
     */
    public String getIp() {
        return (String) get(4);
    }

    /**
     * Setter for <code>boxin_saas_tenant.cas_login_log.type</code>. 登陆日志类型 1:登入 2:登出
     */
    public void setType(UByte value) {
        set(5, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.cas_login_log.type</code>. 登陆日志类型 1:登入 2:登出
     */
    public UByte getType() {
        return (UByte) get(5);
    }

    /**
     * Setter for <code>boxin_saas_tenant.cas_login_log.inserttime</code>. 创建时间
     */
    public void setInserttime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.cas_login_log.inserttime</code>. 创建时间
     */
    public Timestamp getInserttime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>boxin_saas_tenant.cas_login_log.updatetime</code>. 更新时间
     */
    public void setUpdatetime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.cas_login_log.updatetime</code>. 更新时间
     */
    public Timestamp getUpdatetime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>boxin_saas_tenant.cas_login_log.isactive</code>. 逻辑删除
     */
    public void setIsactive(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.cas_login_log.isactive</code>. 逻辑删除
     */
    public Byte getIsactive() {
        return (Byte) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<ULong, ULong, String, String, String, UByte, Timestamp, Timestamp, Byte> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<ULong, ULong, String, String, String, UByte, Timestamp, Timestamp, Byte> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return CasLoginLog.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field2() {
        return CasLoginLog.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CasLoginLog.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CasLoginLog.REAL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CasLoginLog.IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field6() {
        return CasLoginLog.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return CasLoginLog.INSERTTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return CasLoginLog.UPDATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return CasLoginLog.ISACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRealName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component6() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getInserttime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component9() {
        return getIsactive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRealName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value6() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getInserttime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getIsactive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasLoginLogRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasLoginLogRecord value2(ULong value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasLoginLogRecord value3(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasLoginLogRecord value4(String value) {
        setRealName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasLoginLogRecord value5(String value) {
        setIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasLoginLogRecord value6(UByte value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasLoginLogRecord value7(Timestamp value) {
        setInserttime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasLoginLogRecord value8(Timestamp value) {
        setUpdatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasLoginLogRecord value9(Byte value) {
        setIsactive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasLoginLogRecord values(ULong value1, ULong value2, String value3, String value4, String value5, UByte value6, Timestamp value7, Timestamp value8, Byte value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CasLoginLogRecord
     */
    public CasLoginLogRecord() {
        super(CasLoginLog.CAS_LOGIN_LOG);
    }

    /**
     * Create a detached, initialised CasLoginLogRecord
     */
    public CasLoginLogRecord(ULong id, ULong userId, String userName, String realName, String ip, UByte type, Timestamp inserttime, Timestamp updatetime, Byte isactive) {
        super(CasLoginLog.CAS_LOGIN_LOG);

        set(0, id);
        set(1, userId);
        set(2, userName);
        set(3, realName);
        set(4, ip);
        set(5, type);
        set(6, inserttime);
        set(7, updatetime);
        set(8, isactive);
    }
}
