/*
 * This file is generated by jOOQ.
*/
package c.b.s.common.logging.infrastructure.jooq.tables.records;


import c.b.s.common.logging.infrastructure.jooq.tables.CasOperationLog;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * 智牛SaaS平台操作日志表, owner: guiqingqing, manager: zhengkeshuang
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CasOperationLogRecord extends UpdatableRecordImpl<CasOperationLogRecord> implements Record12<ULong, ULong, String, String, ULong, String, String, String, String, Timestamp, Timestamp, Byte> {

    private static final long serialVersionUID = 708430173;

    /**
     * Setter for <code>boxin_saas_tenant.cas_operation_log.id</code>. 主键ID
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.cas_operation_log.id</code>. 主键ID
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>boxin_saas_tenant.cas_operation_log.user_id</code>. 用户ID
     */
    public void setUserId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.cas_operation_log.user_id</code>. 用户ID
     */
    public ULong getUserId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>boxin_saas_tenant.cas_operation_log.user_name</code>. 用户名
     */
    public void setUserName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.cas_operation_log.user_name</code>. 用户名
     */
    public String getUserName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>boxin_saas_tenant.cas_operation_log.real_name</code>. 用户姓名
     */
    public void setRealName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.cas_operation_log.real_name</code>. 用户姓名
     */
    public String getRealName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>boxin_saas_tenant.cas_operation_log.application_id</code>. 应用ID
     */
    public void setApplicationId(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.cas_operation_log.application_id</code>. 应用ID
     */
    public ULong getApplicationId() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>boxin_saas_tenant.cas_operation_log.ip</code>. IP地址
     */
    public void setIp(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.cas_operation_log.ip</code>. IP地址
     */
    public String getIp() {
        return (String) get(5);
    }

    /**
     * Setter for <code>boxin_saas_tenant.cas_operation_log.url</code>. URL
     */
    public void setUrl(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.cas_operation_log.url</code>. URL
     */
    public String getUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>boxin_saas_tenant.cas_operation_log.operation_code</code>. 操作码
     */
    public void setOperationCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.cas_operation_log.operation_code</code>. 操作码
     */
    public String getOperationCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>boxin_saas_tenant.cas_operation_log.operation_value</code>. 操作值
     */
    public void setOperationValue(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.cas_operation_log.operation_value</code>. 操作值
     */
    public String getOperationValue() {
        return (String) get(8);
    }

    /**
     * Setter for <code>boxin_saas_tenant.cas_operation_log.inserttime</code>. 创建时间
     */
    public void setInserttime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.cas_operation_log.inserttime</code>. 创建时间
     */
    public Timestamp getInserttime() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>boxin_saas_tenant.cas_operation_log.updatetime</code>. 更新时间
     */
    public void setUpdatetime(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.cas_operation_log.updatetime</code>. 更新时间
     */
    public Timestamp getUpdatetime() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>boxin_saas_tenant.cas_operation_log.isactive</code>. 逻辑删除
     */
    public void setIsactive(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.cas_operation_log.isactive</code>. 逻辑删除
     */
    public Byte getIsactive() {
        return (Byte) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<ULong, ULong, String, String, ULong, String, String, String, String, Timestamp, Timestamp, Byte> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<ULong, ULong, String, String, ULong, String, String, String, String, Timestamp, Timestamp, Byte> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return CasOperationLog.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field2() {
        return CasOperationLog.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CasOperationLog.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CasOperationLog.REAL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field5() {
        return CasOperationLog.APPLICATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CasOperationLog.IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return CasOperationLog.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return CasOperationLog.OPERATION_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return CasOperationLog.OPERATION_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return CasOperationLog.INSERTTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return CasOperationLog.UPDATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field12() {
        return CasOperationLog.ISACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRealName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component5() {
        return getApplicationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getOperationCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getOperationValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getInserttime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component12() {
        return getIsactive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRealName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value5() {
        return getApplicationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getOperationCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getOperationValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getInserttime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value12() {
        return getIsactive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasOperationLogRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasOperationLogRecord value2(ULong value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasOperationLogRecord value3(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasOperationLogRecord value4(String value) {
        setRealName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasOperationLogRecord value5(ULong value) {
        setApplicationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasOperationLogRecord value6(String value) {
        setIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasOperationLogRecord value7(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasOperationLogRecord value8(String value) {
        setOperationCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasOperationLogRecord value9(String value) {
        setOperationValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasOperationLogRecord value10(Timestamp value) {
        setInserttime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasOperationLogRecord value11(Timestamp value) {
        setUpdatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasOperationLogRecord value12(Byte value) {
        setIsactive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CasOperationLogRecord values(ULong value1, ULong value2, String value3, String value4, ULong value5, String value6, String value7, String value8, String value9, Timestamp value10, Timestamp value11, Byte value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CasOperationLogRecord
     */
    public CasOperationLogRecord() {
        super(CasOperationLog.CAS_OPERATION_LOG);
    }

    /**
     * Create a detached, initialised CasOperationLogRecord
     */
    public CasOperationLogRecord(ULong id, ULong userId, String userName, String realName, ULong applicationId, String ip, String url, String operationCode, String operationValue, Timestamp inserttime, Timestamp updatetime, Byte isactive) {
        super(CasOperationLog.CAS_OPERATION_LOG);

        set(0, id);
        set(1, userId);
        set(2, userName);
        set(3, realName);
        set(4, applicationId);
        set(5, ip);
        set(6, url);
        set(7, operationCode);
        set(8, operationValue);
        set(9, inserttime);
        set(10, updatetime);
        set(11, isactive);
    }
}
