/*
 * This file is generated by jOOQ.
*/
package c.b.s.common.logging.infrastructure.jooq.tables.records;


import c.b.s.common.logging.infrastructure.jooq.tables.TbImportRecord;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * 催收作业系统导入记录表, owner: guiqingqing, manager: zhengkeshuang
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbImportRecordRecord extends UpdatableRecordImpl<TbImportRecordRecord> implements Record18<ULong, String, UByte, String, String, UByte, UInteger, UInteger, ULong, String, Timestamp, Timestamp, Byte, ULong, String, UInteger, UInteger, UInteger> {

    private static final long serialVersionUID = -1441778823;

    /**
     * Setter for <code>boxin_saas_tenant.tb_import_record.id</code>. 主键ID
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_import_record.id</code>. 主键ID
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_import_record.file_name</code>. 文件名
     */
    public void setFileName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_import_record.file_name</code>. 文件名
     */
    public String getFileName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_import_record.import_type</code>. 导入类型 1:案件导入
     */
    public void setImportType(UByte value) {
        set(2, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_import_record.import_type</code>. 导入类型 1:案件导入
     */
    public UByte getImportType() {
        return (UByte) get(2);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_import_record.original_file_url</code>. 原始文件地址
     */
    public void setOriginalFileUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_import_record.original_file_url</code>. 原始文件地址
     */
    public String getOriginalFileUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_import_record.handled_file_url</code>. 处理后的文件地址
     */
    public void setHandledFileUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_import_record.handled_file_url</code>. 处理后的文件地址
     */
    public String getHandledFileUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_import_record.status</code>. 处理状态 0:处理中 1:处理成功 2:处理失败
     */
    public void setStatus(UByte value) {
        set(5, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_import_record.status</code>. 处理状态 0:处理中 1:处理成功 2:处理失败
     */
    public UByte getStatus() {
        return (UByte) get(5);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_import_record.total_count</code>. 总记录数
     */
    public void setTotalCount(UInteger value) {
        set(6, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_import_record.total_count</code>. 总记录数
     */
    public UInteger getTotalCount() {
        return (UInteger) get(6);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_import_record.success_count</code>. 成功记录数
     */
    public void setSuccessCount(UInteger value) {
        set(7, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_import_record.success_count</code>. 成功记录数
     */
    public UInteger getSuccessCount() {
        return (UInteger) get(7);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_import_record.admin_id</code>. 操作人ID
     */
    public void setAdminId(ULong value) {
        set(8, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_import_record.admin_id</code>. 操作人ID
     */
    public ULong getAdminId() {
        return (ULong) get(8);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_import_record.admin_real_name</code>. 操作人姓名
     */
    public void setAdminRealName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_import_record.admin_real_name</code>. 操作人姓名
     */
    public String getAdminRealName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_import_record.inserttime</code>. 创建时间
     */
    public void setInserttime(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_import_record.inserttime</code>. 创建时间
     */
    public Timestamp getInserttime() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_import_record.updatetime</code>. 更新时间
     */
    public void setUpdatetime(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_import_record.updatetime</code>. 更新时间
     */
    public Timestamp getUpdatetime() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_import_record.isactive</code>. 逻辑删除
     */
    public void setIsactive(Byte value) {
        set(12, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_import_record.isactive</code>. 逻辑删除
     */
    public Byte getIsactive() {
        return (Byte) get(12);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_import_record.asset_id</code>. 资方ID
     */
    public void setAssetId(ULong value) {
        set(13, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_import_record.asset_id</code>. 资方ID
     */
    public ULong getAssetId() {
        return (ULong) get(13);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_import_record.task_id</code>. 任务ID
     */
    public void setTaskId(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_import_record.task_id</code>. 任务ID
     */
    public String getTaskId() {
        return (String) get(14);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_import_record.new_user_count</code>. 新户数
     */
    public void setNewUserCount(UInteger value) {
        set(15, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_import_record.new_user_count</code>. 新户数
     */
    public UInteger getNewUserCount() {
        return (UInteger) get(15);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_import_record.old_user_count</code>. 合并老户数
     */
    public void setOldUserCount(UInteger value) {
        set(16, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_import_record.old_user_count</code>. 合并老户数
     */
    public UInteger getOldUserCount() {
        return (UInteger) get(16);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_import_record.total_user_count</code>. 总户数
     */
    public void setTotalUserCount(UInteger value) {
        set(17, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_import_record.total_user_count</code>. 总户数
     */
    public UInteger getTotalUserCount() {
        return (UInteger) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<ULong, String, UByte, String, String, UByte, UInteger, UInteger, ULong, String, Timestamp, Timestamp, Byte, ULong, String, UInteger, UInteger, UInteger> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<ULong, String, UByte, String, String, UByte, UInteger, UInteger, ULong, String, Timestamp, Timestamp, Byte, ULong, String, UInteger, UInteger, UInteger> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return TbImportRecord.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TbImportRecord.FILE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field3() {
        return TbImportRecord.IMPORT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TbImportRecord.ORIGINAL_FILE_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TbImportRecord.HANDLED_FILE_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field6() {
        return TbImportRecord.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field7() {
        return TbImportRecord.TOTAL_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field8() {
        return TbImportRecord.SUCCESS_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field9() {
        return TbImportRecord.ADMIN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return TbImportRecord.ADMIN_REAL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return TbImportRecord.INSERTTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return TbImportRecord.UPDATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field13() {
        return TbImportRecord.ISACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field14() {
        return TbImportRecord.ASSET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return TbImportRecord.TASK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field16() {
        return TbImportRecord.NEW_USER_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field17() {
        return TbImportRecord.OLD_USER_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field18() {
        return TbImportRecord.TOTAL_USER_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component3() {
        return getImportType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getOriginalFileUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getHandledFileUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component7() {
        return getTotalCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component8() {
        return getSuccessCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component9() {
        return getAdminId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getAdminRealName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getInserttime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component13() {
        return getIsactive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component14() {
        return getAssetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getTaskId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component16() {
        return getNewUserCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component17() {
        return getOldUserCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component18() {
        return getTotalUserCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value3() {
        return getImportType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOriginalFileUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getHandledFileUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value7() {
        return getTotalCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value8() {
        return getSuccessCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value9() {
        return getAdminId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getAdminRealName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getInserttime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value13() {
        return getIsactive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value14() {
        return getAssetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getTaskId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value16() {
        return getNewUserCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value17() {
        return getOldUserCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value18() {
        return getTotalUserCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbImportRecordRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbImportRecordRecord value2(String value) {
        setFileName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbImportRecordRecord value3(UByte value) {
        setImportType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbImportRecordRecord value4(String value) {
        setOriginalFileUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbImportRecordRecord value5(String value) {
        setHandledFileUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbImportRecordRecord value6(UByte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbImportRecordRecord value7(UInteger value) {
        setTotalCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbImportRecordRecord value8(UInteger value) {
        setSuccessCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbImportRecordRecord value9(ULong value) {
        setAdminId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbImportRecordRecord value10(String value) {
        setAdminRealName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbImportRecordRecord value11(Timestamp value) {
        setInserttime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbImportRecordRecord value12(Timestamp value) {
        setUpdatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbImportRecordRecord value13(Byte value) {
        setIsactive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbImportRecordRecord value14(ULong value) {
        setAssetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbImportRecordRecord value15(String value) {
        setTaskId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbImportRecordRecord value16(UInteger value) {
        setNewUserCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbImportRecordRecord value17(UInteger value) {
        setOldUserCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbImportRecordRecord value18(UInteger value) {
        setTotalUserCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbImportRecordRecord values(ULong value1, String value2, UByte value3, String value4, String value5, UByte value6, UInteger value7, UInteger value8, ULong value9, String value10, Timestamp value11, Timestamp value12, Byte value13, ULong value14, String value15, UInteger value16, UInteger value17, UInteger value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbImportRecordRecord
     */
    public TbImportRecordRecord() {
        super(TbImportRecord.TB_IMPORT_RECORD);
    }

    /**
     * Create a detached, initialised TbImportRecordRecord
     */
    public TbImportRecordRecord(ULong id, String fileName, UByte importType, String originalFileUrl, String handledFileUrl, UByte status, UInteger totalCount, UInteger successCount, ULong adminId, String adminRealName, Timestamp inserttime, Timestamp updatetime, Byte isactive, ULong assetId, String taskId, UInteger newUserCount, UInteger oldUserCount, UInteger totalUserCount) {
        super(TbImportRecord.TB_IMPORT_RECORD);

        set(0, id);
        set(1, fileName);
        set(2, importType);
        set(3, originalFileUrl);
        set(4, handledFileUrl);
        set(5, status);
        set(6, totalCount);
        set(7, successCount);
        set(8, adminId);
        set(9, adminRealName);
        set(10, inserttime);
        set(11, updatetime);
        set(12, isactive);
        set(13, assetId);
        set(14, taskId);
        set(15, newUserCount);
        set(16, oldUserCount);
        set(17, totalUserCount);
    }
}
