/*
 * This file is generated by jOOQ.
*/
package c.b.s.common.logging.infrastructure.jooq;


import c.b.s.common.logging.infrastructure.jooq.tables.CasLoginLog;
import c.b.s.common.logging.infrastructure.jooq.tables.CasOperationLog;
import c.b.s.common.logging.infrastructure.jooq.tables.TbImportRecord;
import c.b.s.common.logging.infrastructure.jooq.tables.records.CasLoginLogRecord;
import c.b.s.common.logging.infrastructure.jooq.tables.records.CasOperationLogRecord;
import c.b.s.common.logging.infrastructure.jooq.tables.records.TbImportRecordRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.ULong;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>boxin_saas_tenant</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CasLoginLogRecord, ULong> IDENTITY_CAS_LOGIN_LOG = Identities0.IDENTITY_CAS_LOGIN_LOG;
    public static final Identity<CasOperationLogRecord, ULong> IDENTITY_CAS_OPERATION_LOG = Identities0.IDENTITY_CAS_OPERATION_LOG;
    public static final Identity<TbImportRecordRecord, ULong> IDENTITY_TB_IMPORT_RECORD = Identities0.IDENTITY_TB_IMPORT_RECORD;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CasLoginLogRecord> KEY_CAS_LOGIN_LOG_PRIMARY = UniqueKeys0.KEY_CAS_LOGIN_LOG_PRIMARY;
    public static final UniqueKey<CasOperationLogRecord> KEY_CAS_OPERATION_LOG_PRIMARY = UniqueKeys0.KEY_CAS_OPERATION_LOG_PRIMARY;
    public static final UniqueKey<TbImportRecordRecord> KEY_TB_IMPORT_RECORD_PRIMARY = UniqueKeys0.KEY_TB_IMPORT_RECORD_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CasLoginLogRecord, ULong> IDENTITY_CAS_LOGIN_LOG = Internal.createIdentity(CasLoginLog.CAS_LOGIN_LOG, CasLoginLog.ID);
        public static Identity<CasOperationLogRecord, ULong> IDENTITY_CAS_OPERATION_LOG = Internal.createIdentity(CasOperationLog.CAS_OPERATION_LOG, CasOperationLog.ID);
        public static Identity<TbImportRecordRecord, ULong> IDENTITY_TB_IMPORT_RECORD = Internal.createIdentity(TbImportRecord.TB_IMPORT_RECORD, TbImportRecord.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<CasLoginLogRecord> KEY_CAS_LOGIN_LOG_PRIMARY = Internal.createUniqueKey(CasLoginLog.CAS_LOGIN_LOG, "KEY_cas_login_log_PRIMARY", CasLoginLog.ID);
        public static final UniqueKey<CasOperationLogRecord> KEY_CAS_OPERATION_LOG_PRIMARY = Internal.createUniqueKey(CasOperationLog.CAS_OPERATION_LOG, "KEY_cas_operation_log_PRIMARY", CasOperationLog.ID);
        public static final UniqueKey<TbImportRecordRecord> KEY_TB_IMPORT_RECORD_PRIMARY = Internal.createUniqueKey(TbImportRecord.TB_IMPORT_RECORD, "KEY_tb_import_record_PRIMARY", TbImportRecord.ID);
    }
}
