/*
 * This file is generated by jOOQ.
*/
package c.b.s.common.logging.infrastructure.jooq;


import c.b.s.common.logging.infrastructure.jooq.tables.CasLoginLog;
import c.b.s.common.logging.infrastructure.jooq.tables.CasOperationLog;
import c.b.s.common.logging.infrastructure.jooq.tables.TbImportRecord;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in boxin_saas_tenant
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 智牛SaaS平台登录日志表, owner: guiqingqing, manager: zhengkeshuang
     */
    public static final CasLoginLog CAS_LOGIN_LOG = c.b.s.common.logging.infrastructure.jooq.tables.CasLoginLog.CAS_LOGIN_LOG;

    /**
     * 智牛SaaS平台操作日志表, owner: guiqingqing, manager: zhengkeshuang
     */
    public static final CasOperationLog CAS_OPERATION_LOG = c.b.s.common.logging.infrastructure.jooq.tables.CasOperationLog.CAS_OPERATION_LOG;

    /**
     * 催收作业系统导入记录表, owner: guiqingqing, manager: zhengkeshuang
     */
    public static final TbImportRecord TB_IMPORT_RECORD = c.b.s.common.logging.infrastructure.jooq.tables.TbImportRecord.TB_IMPORT_RECORD;
}
