/*
 * This file is generated by jOOQ.
*/
package c.b.s.common.message.infrastructure.jooq.tables.records;


import c.b.s.common.message.infrastructure.jooq.tables.TbMessage;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * 智牛SaaS平台消息表, owner: guiqingqing, manager: zhengkeshuang
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbMessageRecord extends UpdatableRecordImpl<TbMessageRecord> implements Record12<ULong, ULong, ULong, UByte, String, String, String, UByte, Timestamp, Timestamp, Timestamp, Byte> {

    private static final long serialVersionUID = 1930200887;

    /**
     * Setter for <code>boxin_saas_tenant.tb_message.id</code>. 消息ID
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_message.id</code>. 消息ID
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_message.user_id</code>. 用户ID
     */
    public void setUserId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_message.user_id</code>. 用户ID
     */
    public ULong getUserId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_message.application_id</code>. 应用ID
     */
    public void setApplicationId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_message.application_id</code>. 应用ID
     */
    public ULong getApplicationId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_message.type</code>. 消息类型
     */
    public void setType(UByte value) {
        set(3, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_message.type</code>. 消息类型
     */
    public UByte getType() {
        return (UByte) get(3);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_message.subject</code>. 消息标题
     */
    public void setSubject(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_message.subject</code>. 消息标题
     */
    public String getSubject() {
        return (String) get(4);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_message.content</code>. 消息内容
     */
    public void setContent(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_message.content</code>. 消息内容
     */
    public String getContent() {
        return (String) get(5);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_message.file_name</code>. 文件名
     */
    public void setFileName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_message.file_name</code>. 文件名
     */
    public String getFileName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_message.status</code>. 消息状态 0:未读 1:已读
     */
    public void setStatus(UByte value) {
        set(7, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_message.status</code>. 消息状态 0:未读 1:已读
     */
    public UByte getStatus() {
        return (UByte) get(7);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_message.readtime</code>. 已读时间
     */
    public void setReadtime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_message.readtime</code>. 已读时间
     */
    public Timestamp getReadtime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_message.inserttime</code>. 创建时间
     */
    public void setInserttime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_message.inserttime</code>. 创建时间
     */
    public Timestamp getInserttime() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_message.updatetime</code>. 更新时间
     */
    public void setUpdatetime(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_message.updatetime</code>. 更新时间
     */
    public Timestamp getUpdatetime() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>boxin_saas_tenant.tb_message.isactive</code>. 逻辑删除
     */
    public void setIsactive(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>boxin_saas_tenant.tb_message.isactive</code>. 逻辑删除
     */
    public Byte getIsactive() {
        return (Byte) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<ULong, ULong, ULong, UByte, String, String, String, UByte, Timestamp, Timestamp, Timestamp, Byte> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<ULong, ULong, ULong, UByte, String, String, String, UByte, Timestamp, Timestamp, Timestamp, Byte> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return TbMessage.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field2() {
        return TbMessage.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field3() {
        return TbMessage.APPLICATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field4() {
        return TbMessage.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TbMessage.SUBJECT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TbMessage.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TbMessage.FILE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field8() {
        return TbMessage.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return TbMessage.READTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return TbMessage.INSERTTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return TbMessage.UPDATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field12() {
        return TbMessage.ISACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component3() {
        return getApplicationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getSubject();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getReadtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getInserttime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component12() {
        return getIsactive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value3() {
        return getApplicationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSubject();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getFileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getReadtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getInserttime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value12() {
        return getIsactive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbMessageRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbMessageRecord value2(ULong value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbMessageRecord value3(ULong value) {
        setApplicationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbMessageRecord value4(UByte value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbMessageRecord value5(String value) {
        setSubject(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbMessageRecord value6(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbMessageRecord value7(String value) {
        setFileName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbMessageRecord value8(UByte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbMessageRecord value9(Timestamp value) {
        setReadtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbMessageRecord value10(Timestamp value) {
        setInserttime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbMessageRecord value11(Timestamp value) {
        setUpdatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbMessageRecord value12(Byte value) {
        setIsactive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbMessageRecord values(ULong value1, ULong value2, ULong value3, UByte value4, String value5, String value6, String value7, UByte value8, Timestamp value9, Timestamp value10, Timestamp value11, Byte value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbMessageRecord
     */
    public TbMessageRecord() {
        super(TbMessage.TB_MESSAGE);
    }

    /**
     * Create a detached, initialised TbMessageRecord
     */
    public TbMessageRecord(ULong id, ULong userId, ULong applicationId, UByte type, String subject, String content, String fileName, UByte status, Timestamp readtime, Timestamp inserttime, Timestamp updatetime, Byte isactive) {
        super(TbMessage.TB_MESSAGE);

        set(0, id);
        set(1, userId);
        set(2, applicationId);
        set(3, type);
        set(4, subject);
        set(5, content);
        set(6, fileName);
        set(7, status);
        set(8, readtime);
        set(9, inserttime);
        set(10, updatetime);
        set(11, isactive);
    }
}
