/*
 * This file is generated by jOOQ.
*/
package c.b.s.common.message.infrastructure.jooq.tables;


import c.b.s.common.message.infrastructure.jooq.BoxinSaasTenant;
import c.b.s.common.message.infrastructure.jooq.Keys;
import c.b.s.common.message.infrastructure.jooq.tables.records.TbMesageFileRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbMesageFile extends TableImpl<TbMesageFileRecord> {

    private static final long serialVersionUID = -718427902;

    /**
     * The reference instance of <code>boxin_saas_tenant.tb_mesage_file</code>
     */
    public static final TbMesageFile TB_MESAGE_FILE = new TbMesageFile();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TbMesageFileRecord> getRecordType() {
        return TbMesageFileRecord.class;
    }

    /**
     * The column <code>boxin_saas_tenant.tb_mesage_file.id</code>. 主键
     */
    public static final TableField<TbMesageFileRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), TB_MESAGE_FILE, "主键");

    /**
     * The column <code>boxin_saas_tenant.tb_mesage_file.message_id</code>. 批量下载语音文件id
     */
    public static final TableField<TbMesageFileRecord, Long> MESSAGE_ID = createField("message_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), TB_MESAGE_FILE, "批量下载语音文件id");

    /**
     * The column <code>boxin_saas_tenant.tb_mesage_file.file_name</code>. 压缩文件名
     */
    public static final TableField<TbMesageFileRecord, String> FILE_NAME = createField("file_name", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), TB_MESAGE_FILE, "压缩文件名");

    /**
     * The column <code>boxin_saas_tenant.tb_mesage_file.inserttime</code>. 插入时间
     */
    public static final TableField<TbMesageFileRecord, Timestamp> INSERTTIME = createField("inserttime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), TB_MESAGE_FILE, "插入时间");

    /**
     * The column <code>boxin_saas_tenant.tb_mesage_file.updatetime</code>. 更新时间
     */
    public static final TableField<TbMesageFileRecord, Timestamp> UPDATETIME = createField("updatetime", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), TB_MESAGE_FILE, "更新时间");

    /**
     * The column <code>boxin_saas_tenant.tb_mesage_file.isactive</code>. 生效与否
     */
    public static final TableField<TbMesageFileRecord, Byte> ISACTIVE = createField("isactive", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.TINYINT)), TB_MESAGE_FILE, "生效与否");

    /**
     * No further instances allowed
     */
    private TbMesageFile() {
        this(DSL.name("tb_mesage_file"), null);
    }

    private TbMesageFile(Name alias, Table<TbMesageFileRecord> aliased) {
        this(alias, aliased, null);
    }

    private TbMesageFile(Name alias, Table<TbMesageFileRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BoxinSaasTenant.BOXIN_SAAS_TENANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TbMesageFileRecord, Long> getIdentity() {
        return Keys.IDENTITY_TB_MESAGE_FILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TbMesageFileRecord> getPrimaryKey() {
        return Keys.KEY_TB_MESAGE_FILE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TbMesageFileRecord>> getKeys() {
        return Arrays.<UniqueKey<TbMesageFileRecord>>asList(Keys.KEY_TB_MESAGE_FILE_PRIMARY);
    }
}
